## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [21]:
n = 15
np.arange(n-1, -1, -1)

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [24]:
n = 8
x = np.diag(np.arange(n, -1, -1))
x

array([[8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
np.trace(x)

36

## Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [26]:
from numpy import linalg

In [27]:
m = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
n = np.array([4, 12, -3])

In [28]:
linalg.solve(m, n)

array([ 0.46666667,  3.84444444, -5.55555556])

## Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [66]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [67]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [89]:
from numpy import linalg

cos = np.array([])

next_user_length = np.linalg.norm(next_user_stats) # длина вектора next_user_stats

for user in users_stats:
    user_length = np.linalg.norm(user) # длина вектора для каждого покупателя из users_stats
    cos = np.append(cos, np.dot(user, next_user_stats) / (user_length * next_user_length)) # рассчитаем косинус и добаляем его в np array

for i, n in enumerate(cos):
    if n == np.amax(cos): # значения косинуса изменяются от 0 до 1, ищем максимально приближенное к 1.
        print(f'ID пользователя с аналогичными предпочтениями: {i+1}')    

ID пользователя с аналогичными предпочтениями: 8
